# Generated by Django 3.1.1 on 2020-09-16 10:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100, unique=True, verbose_name='відношення')),
            ],
            options={
                'verbose_name': 'відношення родича',
                'verbose_name_plural': 'Відношення родичів',
            },
        ),
        migrations.CreateModel(
            name='Surname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, unique=True, verbose_name='прізвище')),
            ],
            options={
                'verbose_name': 'Прізвище',
                'verbose_name_plural': 'Прізвища',
            },
        ),
        migrations.CreateModel(
            name='FamillieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="ім'я")),
                ('date', models.DateField(verbose_name='вік')),
                ('address', models.CharField(db_index=True, max_length=200)),
                ('point', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', geography=True, srid=4326)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famillies.relationtype', verbose_name='відношення')),
                ('surname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famillies.surname', verbose_name='прізвище')),
            ],
            options={
                'verbose_name': 'Родич',
                'verbose_name_plural': 'Родичі',
            },
        ),
    ]
